### ISSUE TITLE
Invalid initialValue will crash app even after a valid value is provided

### ISSUE THREAD

**Issue by cvburgess** [donavon/use-dark-mode#31]
I can get this to work nicely in Chrome and Chromium-based browsers, but it seems `use-persisted-state` is having an issue with Firefox and crashing the entire app.

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
get
node_modules/use-persisted-state/dist/use-persisted-state.m.js:29

  26 | return {
  27 |   get: function (n, e) {
  28 |     var r = t.getItem(n);
> 29 |     return null === r ? "function" == typeof e ? e() : e : JSON.parse(r);
     | ^  30 |   },
  31 |   set: function (n, e) {
  32 |     t.setItem(n, JSON.stringify(e));

./node_modules/use-persisted-state/dist/use-persisted-state.m.js/</__webpack_exports__.default/</</s<
node_modules/use-persisted-state/dist/use-persisted-state.m.js:43

  40 |     f = o.set,
  41 |     l = e(null),
  42 |     s = t(function () {
> 43 |   return a(i, u);
     | ^  44 | }),
  45 |     v = s[0],
  46 |     g = s[1];
```

**Comment by cvburgess** [comment]
This may not be browser-realed, but just luck.

I used a simple Create-React-App with the code from the Readme to test.

It seems if I ever had an invalid value for the hook, it will forever break the app. For instance, i originally called `useDarkMode()` without any arguments and the only way to prevent it from crashing the app after fixing that... is to nuke local storage.

It would be nice to fail gracefully back to the default value if storage get corrpted to prevent crashes.

**Comment by JamesSingleton** [comment]
Hi @cvburgess,

Do you have a code sample for this? I just created a new `create-react-app` with the following code:

```jsx
import React from 'react';
import useDarkMode from 'use-dark-mode';
import './App.css';

function App() {
  const darkMode = useDarkMode();
  return (
    <div className="App">
      <button type="button" onClick={darkMode.disable}>
        ☀
      </button>
      <button type="button" onClick={darkMode.enable}>
        ☾
      </button>
    </div>
  );
}

export default App;
```

And it defaults to dark mode. This was in Chrome `v77.0.3865.120` as well as FireFox `v70.0.1`.

Everything worked correctly and the app didn't crash.

**Comment by cvburgess** [comment]
Strange, my code was basically identical.

Close this i guess - must have been a ghost in the wire.
