### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by voxvici** [donavon/use-dark-mode#69]
```
npm ERR! While resolving: test@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from use-dark-mode@2.3.1
npm ERR! node_modules/use-dark-mode
npm ERR!   use-dark-mode@"*" from the root project
```

**Comment by denvercoder** [comment]
Why did you close this? Did you find a resolution? I'm having the same issue.

**Comment by denvercoder** [comment]
> Why did you close this? Did you find a resolution? I'm having the same issue.

I just downgraded from React 17.0.1 to React "^16.8.0"

in case anyone else makes it here. ;)

**Comment by voxvici** [comment]
Force it, works well

**Comment by djD-REK** [comment]
Yeah the package.json file for use-dark-mode should probably be updated to
^17.0.1, I wouldn't anticipate any conflicts.

**Comment by horainuri** [comment]
No reason to close this issue as the PR #68 has not been merged since months, is this project dead?

**Comment by styfrombrest** [comment]
@hiroyukinuri looks like it is, try this workaround, works for me:
```
"overrides": {
    "use-dark-mode": {
      "react": "^17.0.0 || ^18.0.0"
    }
  }
```
